# Change these first
owner: parti-coop # Your GitHub organization or username, where this repository lives
repo: parti-mx-upptime # The name of this repository

sites:
  - name: 빠띠
    url: https://parti.coop
  - name: 빠띠 그룹스
    url: https://parti.xyz
  - name: 빠띠 타운홀
    url: https://townhall.kr/
  - name: 빠띠 믹스
    url: https://parti.mx
  - name: 빠띠 캠페인즈
    url: https://campaigns.kr
  - name: 데이터퍼블릭
    url: https://datapublic.kr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /parti-mx-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
